config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'places#index'
	resources :places do
	  get 'page/:page', action: :index, on: :collection
		resources :comments, only: :create
		resources :photos
	end
  devise_for :users
	resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  validates :rating, presence: true

  RATINGS = {
    'one star':     '1_star',
    'two stars':    '2_stars',
    'three stars':  '3_stars',
    'four stars':   '4_stars',
    'five stars':   '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver_now
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  belongs_to :place
  mount_uploader :picture, PictureUploader

  validates :picture, presence: true

  default_scope { order(created_at: :asc) }
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :photos

  geocoded_by :full_address
  after_validation :geocode

  validates :name, :address, :description, presence: true
  validates :name, length: { minimum: 4 }

  def full_address
    [name, address].join(' ')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :picture)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = current_place
    @place.photos.create(photo_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  def edit
    @place = current_place
    @photo = current_photo
  end

  def update
    @place = current_place
    @photo = current_photo
    if @photo.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end

    @photo.update_attributes(photo_params)
    if @photo.valid?
      redirect_to place_path(@place)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = current_place
    @photo = current_photo
    if @photo.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end

    @photo.destroy
    redirect_to place_path(@place)
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :picture)
  end

  def current_place
    Place.find(params[:place_id])
  end

  def current_photo
    current_place.photos.find(params[:id])
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

	def index
		@places = Place.page(params[:page]).order(:id).per(1)
		@pagination_window = (@places.first_page? || @places.last_page?) ? 2 : 1
	end

	def new
		@place = Place.new
	end

	def create
		@place = current_user.places.create(place_params)
		if @place.valid?
			redirect_to root_path
		else
			render :new, status: :unprocessable_entity
		end
	end

	def show
		@place = current_place
		@comment = Comment.new
		@photo = Photo.new
	end

	def edit
		@place = current_place
	end

	def update
		@place = current_place
		if @place.user != current_user
			return render plain: 'Not Allowed', status: :forbidden
		end

		@place.update_attributes(place_params)
		if @place.valid?
			redirect_to root_path
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@place = current_place
		if @place.user != current_user
			return render plain: 'Not Allowed', status: :forbidden
		end

		@place.destroy
		redirect_to root_path
	end

	private

	def current_place
		Place.find(params[:id])
	end

	def place_params
		params.require(:place).permit(:name, :description, :address)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/places_helper.rb
module PlacesHelper
  def slider_image_tag(path, *image_tag_params)
    image_tag "#{ENV['SLIDER']}/#{path}", image_tag_params[0]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>nomStar</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head_place_map_js %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark align-items-baseline <%= yield :navbar_class %>">
      <%= link_to 'nomStar', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNavbarToggler" aria-controls="mainNavbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="mainNavbarToggler">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_place_path, class: 'nav-link' do %>
              <%= icon('fas', 'plus-circle') %>
              New Place
            <% end %>
          </li>
        </ul>

        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>

      </div>

    </nav>

    <% if notice.present? %>
      <p class="alert alert-info text-center rounded-0"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger text-center rounded-0"><%= alert %></p>
    <% end %>

    <%= yield :body_before_main_content %>
    <div class="nm-main-content container">
      <%= yield %>
    </div>

    <div class="nm-main-footer"></div>
  </body>
</html>

app/views/photos/_slider.html.erb
<% slider_id = "nm_#{type}_slider_#{id}" %>

<div class="nm-photo-slider--outer nm-<%= type %>-slider">
  <%= icon('fas', 'sort', class: 'nm-photo-slider--fullscreen-toggle') %>
  <div class="nm-photo-slider--inner" id="<%= slider_id %>">
    <%= render "#{type}_slides" %>
  </div>
</div>

<script>
  jQuery(function() { nm_initSlider('<%= slider_id %>') })
</script>

app/views/photos/edit.html.erb
<div class="nm-section-box">
  <h1 class="mb-4">Edit photo for <%= @place.name %></h1>
  <%= simple_form_for @photo, url: place_photo_path(@place, @photo), html: { class: 'row' } do |f| %>
    <div class="col-lg-6">
      <div class="nm-photo-edit--preview">
        <%= image_tag(@photo.picture_url, class: 'nm-photo-edit--preview-img') if @photo.picture? %>
      </div>
    </div>
    <div class="col-lg-6 pt-4">
      <%= f.input :picture %>
      <%= f.hidden_field :picture_cache %>
      <%= f.input :caption %>
      <div class="form-group mt-4 mb-0">
        <%= link_to 'Remove photo', place_photo_path(@place, @photo), method: :delete,
              data: {confirm: 'Are you sure you want to delete this photo?'},
              class: 'btn btn-outline-danger' %>
        <%= f.submit 'Update photo', class: 'btn btn-primary float-right' %>
      </div>
    </div>
  <% end %>
</div>

app/views/places/_comment.html.erb
<div class="nm-a-comment">
  <blockquote>
    <% if comment.humanized_rating.present? %>
      <strong class="nm-a-comment--rating"><%= comment.humanized_rating %></strong>
    <% end %>
    <%= comment.message %>
  </blockquote>
  <p class="nm-a-comment--email"><%= comment.user.email %></p>
</div>

app/views/places/_comment_item.html.erb
<div class="nm-a-comment">
  <blockquote>
    <% if comment.humanized_rating.present? %>
      <strong class="nm-a-comment--rating"><%= comment.humanized_rating %></strong>
    <% end %>
    <%= comment.message %>
  </blockquote>
  <p class="nm-a-comment--email"><%= comment.user.email %></p>
</div>

app/views/places/_comments.html.erb
<section class="nm-place-comments nm-section-plain nm-width-md">

  <header class="nm-place-comments--header">

    <h2 class="mb-3">Comments</h2>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#nm_newCommentModal">
      <% if @place.comments.present? %> Add a comment <% else %> Be the first to comment! <% end %>
    </button>

    <!-- Modal -->
    <div class="nm-comment-new--modal modal fade" id="nm_newCommentModal" tabindex="-1" role="dialog" aria-labelledby="nm_newCommentModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="nm_newCommentModalLabel">Add a comment</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
            <div class="modal-body">
              <h5 class="mb-4"><%= @place.name %></h5>
              <%= f.input :message %>
              <%= f.input :rating, as: :select, collection: Comment::RATINGS,
                    wrapper_html: { class: 'nm-comment-new--modal-rating' } %>
            </div>
            <div class="nm-comment-new--modal-footer modal-footer">
              <%= f.submit 'Add a comment', class: 'btn btn-primary' %>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  </header>

  <% @place.comments.each do |comment| %>
    <%= render 'comment', comment: comment %>
  <% end %>

</section>

app/views/places/_footer.erb
<div class="nm-place-footer">
  <%= render 'photo_new' %>
  <%# Display Edit and Remove links only if the user is logged-in
       and is the author of this Place %>
  <% if current_user && current_user == @place.user %>
    <%= link_to 'Edit Place', edit_place_path(@place), class: 'btn btn-outline-primary' %>
  <% else %>
      <div class="nm-place-footer--credit">Place submitted by: <%= @place.user.email %></div>
  <% end %>
</div>

app/views/places/_index_slider_items.html.erb
<% [
  { filename: 'VLT-NGC-1232.jpg',
    caption: 'Spiral galaxy NGC 1232. Produced in 1998 using one of the Very Large Telescopes of Paranal Observatory.'
  },
  { filename: 'VLT-NGC-3372-Carina-Nebula.jpg',
    caption: '"Carina Nebula" NGC 3372. Produced in 2012 using one of the Very Large Telescopes of Paranal Observatory.'
  },
  { filename: 'GTC-NGC-891.jpg',
    caption: 'Spiral galaxy NGC 891. Produced in 2017 using the Gran Telescopio of Roque de los Muchachos Observatory.'
  },
  { filename: 'GTC-M1-Crab-Nebula.jpg',
    caption: '"The Crab Nebula" (M1). Produced in 2011 using the Gran Telescopio of Roque de los Muchachos Observatory.'
  },
].each do |photo| %>
  <div class="nm-photo-slide">
    <div class="nm-photo-slide--img-outer">
      <%= slider_image_tag "index/#{photo[:filename]}", class: 'nm-photo-slide--img' %>
    </div>
    <div class="nm-photo-slide--caption">
      <%= photo[:caption] %>
    </div>
  </div>
<% end %>

app/views/places/_index_slides.html.erb
<% [
  { filename: 'VLT-NGC-1232.jpg',
    caption: 'Spiral galaxy NGC 1232. Produced in 1998 using one of the Very Large Telescopes of Paranal Observatory.'
  },
  { filename: 'VLT-NGC-3372-Carina-Nebula.jpg',
    caption: '"Carina Nebula" NGC 3372. Produced in 2012 using one of the Very Large Telescopes of Paranal Observatory.'
  },
  { filename: 'GTC-NGC-891.jpg',
    caption: 'Spiral galaxy NGC 891. Produced in 2017 using the Gran Telescopio of Roque de los Muchachos Observatory.'
  },
  { filename: 'GTC-M1-Crab-Nebula.jpg',
    caption: '"The Crab Nebula" (M1). Produced in 2011 using the Gran Telescopio of Roque de los Muchachos Observatory.'
  },
].each do |photo| %>
  <div class="nm-photo-slide">
    <div class="nm-photo-slide--img-outer">
      <%= slider_image_tag "index/#{photo[:filename]}", class: 'nm-photo-slide--img' %>
      <%= slider_image_tag "index/#{photo[:filename]}", class: 'nm-photo-slide--img nm-index-slide--img-blur-overlay' %>
    </div>
    <div class="nm-photo-slide--caption nm-index-slide--caption">
      <%= photo[:caption] %>
    </div>
  </div>
<% end %>

app/views/places/_map.erb
<% content_for :head_place_map_js do %>
  <%# The map.js script must be inline and precede
      the Google Maps API and the nm_callback_place_map()
      to guarantee availability when they run %>
  <script><%= render 'map.js' %></script>
  <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyBd9QjG4qnkruz9Mw6uuFOeg-rR6SOM3r8&callback=nm_callback_google_maps_api', async: true, defer: true %>
<% end %>

<div id="nm-google-map"></div>

<script>
  // Try to load the Google Map
  nm_callback_place_map({
    lat: <%= @place.latitude %>,
    lng: <%= @place.longitude %>
  });
</script>

app/views/places/_map.js.erb
// Allow maps to load when using Ajax (Turbolinks)
// even when the main Google Maps API script doesn't reload
// and regardless whether the API or the script in Show Place view loads first

nm_GOOGLE_MAPS_API_LOADED = false;
nm_PLACE_COORDINATES = false;

// Called by Google Maps API, when it loads
function nm_callback_google_maps_api() {
  if (nm_PLACE_COORDINATES) nm_initMap(nm_PLACE_COORDINATES);
  // The script in Show Place view will run its callback function
  // on every Ajax reload and will need to know that the API has loaded
  nm_GOOGLE_MAPS_API_LOADED = true;
}


// Called by the script in Show Place view, when it loads
function nm_callback_place_map(placeCoordinates) {
  if (nm_GOOGLE_MAPS_API_LOADED) {
    nm_initMap(placeCoordinates);
  }
  else {
    // Remember globally to be used later when Google Maps API loads
    // and calls nm_initMap() through its callback function
    nm_PLACE_COORDINATES = placeCoordinates;
  }
}


// Called only by the callback functions above
function nm_initMap(placeCoordinates) {

  var map = new google.maps.Map(document.getElementById('nm-google-map'), {
    zoom: 12,
    center: placeCoordinates,
    mapTypeId: 'hybrid',
    mapTypeControlOptions: {
      style: google.maps.MapTypeControlStyle.DROPDOWN_MENU,
      mapTypeIds: ['hybrid', 'terrain']
    }
  });

  var marker = new google.maps.Marker({
    position: placeCoordinates,
    map: map
  });

}

app/views/places/_photo_new.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#nm_newPhotoModal">
  Add a photo
</button>

<!-- Modal -->
<div class="nm-photo-new--modal modal fade" id="nm_newPhotoModal" tabindex="-1" role="dialog" aria-labelledby="nm_newPhotoModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="nm_newPhotoModalLabel">Add a photo</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
        <div class="modal-body">
          <h5 class="mb-4"><%= @place.name %></h5>
          <%= image_tag(@photo.picture_url) if @photo.picture? %>
          <%= f.input :picture %>
          <%= f.hidden_field :picture_cache %>
          <%= f.input :caption %>
        </div>
        <div class="nm-photo-new--modal-footer modal-footer">
          <%= f.submit 'Add a photo', class: 'btn btn-primary' %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/places/_photo_slider.html.erb
<% slider_id = "nm_#{type}_slider_#{id}" %>

<div class="nm-photo-slider--outer nm-<%= type %>-slider">
  <%= icon('fas', 'sort', class: 'nm-photo-slider--fullscreen-toggle') %>
  <div class="nm-photo-slider--inner" id="<%= slider_id %>">
    <%= render "#{type}_slider_items" %>
  </div>
</div>

<script>
  jQuery(function() { nm_initSlider('<%= slider_id %>') })
</script>

app/views/places/_place_slider_items.html.erb
<% @place.photos.each do |photo| %>
  <div class="nm-photo-slide">
    <div class="nm-photo-slide--img-outer">
      <%= image_tag photo.picture, class: 'nm-photo-slide--img' %>
    </div>
    <div class="nm-photo-slide--caption">
      <%= photo.caption %>
      <% if current_user && current_user == photo.user %>
        <%= link_to 'Edit photo', edit_place_photo_path(@place, photo),
              class: 'nm-photo-slide--caption-a float-right' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/places/_place_slides.html.erb
<% @place.photos.each do |photo| %>
  <div class="nm-photo-slide">
    <div class="nm-photo-slide--img-outer">
      <%= image_tag photo.picture, class: 'nm-photo-slide--img' %>
    </div>
    <div class="nm-photo-slide--caption">
      <%= photo.caption %>
      <% if current_user && current_user == photo.user %>
        <%= link_to 'Edit photo', edit_place_photo_path(@place, photo),
              class: 'nm-photo-slide--caption-a float-right' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/places/edit.html.erb
<div class="nm-section-box nm-width-md">
  <h1 class="mb-4">Edit Your Place</h1>
  <%= simple_form_for @place, wrapper: :horizontal_form do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <div class="form-group mt-4">
      <%= link_to 'Remove Place', place_path(@place), method: :delete,
            data: {confirm: "Are you sure you want to delete the place \"#{@place.name}\"?"},
            class: 'btn btn-outline-danger' %>
      <%= f.submit 'Update', class: 'btn btn-primary float-right' %>
    </div>
  <% end %>
</div>

app/views/places/index.html.erb
<% content_for :navbar_class, 'nm-index-navbar' %>

<% content_for :body_before_main_content do %>
	<%= render 'photos/slider', type: 'index', id: 'places' %>
<% end %>

<div class="d-flex justify-content-center">
	<%= paginate @places, window: 0, outer_window: @pagination_window %>
</div>

<% @places.each do |place| %>
	<div class="nm-index-place nm-section-box row">

		<div class="nm-index-photo--featured col-md-5">
			<% if place.photos.present? %>
				<%= link_to place_path(place) do %>
					<%= image_tag place.photos.first.picture, class: 'nm-index-photo--img' %>
				<% end %>
			<% end %>
		</div>

		<div class="nm-index-place--text col-md-7">
			<h1>
				<%= link_to place.name, place_path(place) %>
			</h1>
			<p class="font-italic">
				<%= place.address %>
			</p>
			<p>
				<%= place.description %>
			</p>

			<% if place.comments.present? %>
				<%= render 'comment', comment: place.comments.last %>
			<% end %>
		</div>

	</div>
<% end %>

app/views/users/_comment.html.erb
<div class="nm-user-comment col-md-6">
  <h3 class="nm-user-comment--place-name"><%= link_to comment.place.name, place_path(comment.place) %></h3>
  <blockquote class="nm-a-comment">
    <% if comment.humanized_rating.present? %>
      <strong class="nm-a-comment--rating"><%= comment.humanized_rating %></strong>
    <% end %>
    <%= comment.message %>
  </blockquote>
</div>

app/views/users/_comment_item.html.erb
<div class="nm-user-comment--outer col-md-6">
  <h3 class="nm-user-comment--place-name"><%= link_to comment.place.name, place_path(comment.place) %></h3>
  <div class="nm-a-comment">
    <blockquote>
      <% if comment.humanized_rating.present? %>
        <strong class="nm-a-comment--rating"><%= comment.humanized_rating %></strong>
      <% end %>
      <%= comment.message %>
    </blockquote>
    <p class="nm-a-comment--email"><%= comment.user.email %></p>
  </div>
</div>

app/views/users/show.html.erb
<div class="nm-user-info nm-section-box nm-width-md row">
    <div class="nm-user-info--identity col-md-4">
      <%= icon('fas', 'user-astronaut', class: 'nm-user-info--avatar') %>
    </div>
  <div class="nm-user-info--stats col-md-8">
    <p class="nm-user-info--email"><%= @user.email %></p>
    <p class="nm-user-info--member-since">Member since: <%= @user.created_at.strftime("%B %d, %Y") %></p>
    <hr>
    <div class="nm-user-info--review-counts">
      <p><%= @user.comments.count %> total comments</p>
      <p><%= @user.comments.where(rating: '5_stars').count %> total 5 star reviews</p>
    </div>
  </div>
</div>

<div class="nm-user-comments--outer nm-section-plain nm-width-md">
  <h2>My Comments</h2>
  <div class="nm-user-comments row">
    <% @user.comments.each do |comment| %>
      <%= render 'comment', comment: comment %>
    <% end %>
  </div>
</div>

<div class="nm-user-places nm-section-plain nm-width-md">
  <h2 class="d-inline-block">My Places</h2>
    <% @user.places.each do |place| %>
      <div class="nm-user-place nm-section-box">
        <h3><%= link_to place.name, place_path(place) %></h3>
        <p class="font-italic">
          <%= place.address %>
        </p>
        <p>
          <%= place.description %>
        </p>
        <% if place.comments.present? %>
          <%= render 'places/comment', comment: place.comments.last %>
        <% end %>
      </div>
    <% end %>
</div>